"""empty message

Revision ID: 03597311eadf
Revises: 72416ab28e0c
Create Date: 2021-03-15 19:43:40.939389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03597311eadf'
down_revision = '72416ab28e0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_tag')
    # ### end Alembic commands ###
