"""empty message

Revision ID: 03c20445104d
Revises: 467d54d2129b
Create Date: 2021-03-18 11:10:23.224158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03c20445104d'
down_revision = '467d54d2129b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('slug', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'slug')
    # ### end Alembic commands ###
