"""empty message

Revision ID: 10cbaee649dd
Revises: 2d9bd4b3a39c
Create Date: 2021-03-29 00:25:13.037776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10cbaee649dd'
down_revision = '2d9bd4b3a39c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchers', sa.Column('account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'watchers', 'account', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'watchers', type_='foreignkey')
    op.drop_column('watchers', 'account_id')
    # ### end Alembic commands ###
