"""empty message

Revision ID: 262672b5b13c
Revises: 85ac154c316b
Create Date: 2021-03-17 00:54:10.255362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '262672b5b13c'
down_revision = '85ac154c316b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_comment', sa.Column('course_review_id', sa.Integer(), nullable=True))
    op.drop_constraint('review_comment_review_id_fkey', 'review_comment', type_='foreignkey')
    op.create_foreign_key(None, 'review_comment', 'course_review', ['course_review_id'], ['id'], ondelete='CASCADE')
    op.drop_column('review_comment', 'review_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_comment', sa.Column('review_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'review_comment', type_='foreignkey')
    op.create_foreign_key('review_comment_review_id_fkey', 'review_comment', 'course_review', ['review_id'], ['id'], ondelete='CASCADE')
    op.drop_column('review_comment', 'course_review_id')
    # ### end Alembic commands ###
