"""empty message

Revision ID: 2d9bd4b3a39c
Revises: 4eec541f41b3
Create Date: 2021-03-29 00:25:00.340444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d9bd4b3a39c'
down_revision = '4eec541f41b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchers', sa.Column('course_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'watchers', 'course', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'watchers', type_='foreignkey')
    op.drop_column('watchers', 'course_id')
    # ### end Alembic commands ###
