"""empty message

Revision ID: 38b88cbd63bc
Revises: f7685ea8c8f2
Create Date: 2021-03-17 01:31:09.346185

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '38b88cbd63bc'
down_revision = 'f7685ea8c8f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_comment')
    op.drop_table('course_tag')
    op.create_foreign_key(None, 'course', 'course_category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.create_table('course_tag',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='course_tag_course_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='course_tag_pkey'),
    sa.UniqueConstraint('text', name='course_tag_text_key')
    )
    op.create_table('review_comment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('course_review_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='review_comment_pkey')
    )
    # ### end Alembic commands ###
