"""empty message

Revision ID: 461e6167450b
Revises: ea1c7243af71
Create Date: 2021-03-28 13:34:55.422949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '461e6167450b'
down_revision = 'ea1c7243af71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'review_comment', 'course_review', ['review_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review_comment', type_='foreignkey')
    op.drop_table('course_review')
    # ### end Alembic commands ###
