"""empty message

Revision ID: 4bbabf1d0388
Revises: 60e1c7ce6466
Create Date: 2021-03-22 21:25:49.413880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bbabf1d0388'
down_revision = '60e1c7ce6466'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('video_length', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'video_length')
    # ### end Alembic commands ###
