"""empty message

Revision ID: 4eec541f41b3
Revises: 50f610f15e90
Create Date: 2021-03-29 00:24:45.610883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eec541f41b3'
down_revision = '50f610f15e90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchers', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_constraint('watchers_course_id_fkey', 'watchers', type_='foreignkey')
    op.drop_constraint('watchers_account_id_fkey', 'watchers', type_='foreignkey')
    op.drop_column('watchers', 'course_id')
    op.drop_column('watchers', 'account_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchers', sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('watchers', sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('watchers_account_id_fkey', 'watchers', 'account', ['account_id'], ['id'])
    op.create_foreign_key('watchers_course_id_fkey', 'watchers', 'course', ['course_id'], ['id'])
    op.drop_column('watchers', 'id')
    # ### end Alembic commands ###
