"""empty message

Revision ID: 60e1c7ce6466
Revises: ffd9be783085
Create Date: 2021-03-21 16:52:00.275514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60e1c7ce6466'
down_revision = 'ffd9be783085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_category', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_category', 'image')
    # ### end Alembic commands ###
