"""empty message

Revision ID: 6c1d6b3957d5
Revises: 262672b5b13c
Create Date: 2021-03-17 01:28:19.494107

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6c1d6b3957d5'
down_revision = '262672b5b13c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_review')
    op.drop_table('course_tag')
    op.drop_table('review_comment')
    op.drop_constraint('course_category_id_fkey', 'course', type_='foreignkey')
    op.create_foreign_key(None, 'course', 'course_category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.create_foreign_key('course_category_id_fkey', 'course', 'course_review', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_table('review_comment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('course_review_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_review_id'], ['course_review.id'], name='review_comment_course_review_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='review_comment_pkey')
    )
    op.create_table('course_tag',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='course_tag_course_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='course_tag_pkey'),
    sa.UniqueConstraint('text', name='course_tag_text_key')
    )
    op.create_table('course_review',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rating', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='course_review_course_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='course_review_pkey')
    )
    # ### end Alembic commands ###
