"""empty message

Revision ID: 718ec7aeb1a0
Revises: 4bbf4e99bc97
Create Date: 2021-03-28 12:30:56.844009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '718ec7aeb1a0'
down_revision = '4bbf4e99bc97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_review', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_review', 'email')
    # ### end Alembic commands ###
