"""empty message

Revision ID: 788507884df9
Revises: 8cffc1b53d9c
Create Date: 2021-03-17 15:41:54.511670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '788507884df9'
down_revision = '8cffc1b53d9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('video', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'video')
    # ### end Alembic commands ###
