"""empty message

Revision ID: 85ac154c316b
Revises: 3b8a115941a7
Create Date: 2021-03-17 00:42:21.668231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85ac154c316b'
down_revision = '3b8a115941a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'course', 'course_review', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_column('course', 'category_id')
    # ### end Alembic commands ###
