"""empty message

Revision ID: 8ab5ce7599e5
Revises: 4bbabf1d0388
Create Date: 2021-03-24 00:23:07.674971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ab5ce7599e5'
down_revision = '4bbabf1d0388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('course', sa.Column('skill_level_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'course', 'course', ['skill_level_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_column('course', 'skill_level_id')
    op.drop_table('skill_level')
    # ### end Alembic commands ###
