"""empty message

Revision ID: a16240a474e5
Revises: 8ab5ce7599e5
Create Date: 2021-03-24 00:31:36.491182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a16240a474e5'
down_revision = '8ab5ce7599e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('course_skill_level_id_fkey', 'course', type_='foreignkey')
    op.create_foreign_key(None, 'course', 'skill_level', ['skill_level_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.create_foreign_key('course_skill_level_id_fkey', 'course', 'course', ['skill_level_id'], ['id'])
    # ### end Alembic commands ###
