"""empty message

Revision ID: a4ce1176c665
Revises: 03597311eadf
Create Date: 2021-03-15 19:46:36.410177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4ce1176c665'
down_revision = '03597311eadf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('icon', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'icon')
    # ### end Alembic commands ###
