"""empty message

Revision ID: a9c805d4ec4e
Revises: 6bf8bad8a387
Create Date: 2021-03-15 20:01:23.536929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a9c805d4ec4e'
down_revision = '6bf8bad8a387'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('review')
    op.drop_constraint('review_comment_review_id_fkey', 'review_comment', type_='foreignkey')
    op.create_foreign_key(None, 'review_comment', 'course_review', ['review_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review_comment', type_='foreignkey')
    op.create_foreign_key('review_comment_review_id_fkey', 'review_comment', 'review', ['review_id'], ['id'])
    op.create_table('review',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rating', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='review_course_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='review_pkey')
    )
    op.drop_table('course_review')
    # ### end Alembic commands ###
