"""empty message

Revision ID: b201019b6302
Revises: 12a89e5ba540
Create Date: 2021-03-16 03:34:23.656854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b201019b6302'
down_revision = '12a89e5ba540'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('account', 'last_name')
    op.drop_column('account', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('account', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('account', 'name')
    # ### end Alembic commands ###
