"""empty message

Revision ID: c1b26370fe31
Revises: 03c20445104d
Create Date: 2021-03-19 03:49:11.421175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1b26370fe31'
down_revision = '03c20445104d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_learning_objectives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_learning_objectives')
    # ### end Alembic commands ###
