"""empty message

Revision ID: dd5cefabf099
Revises: 788507884df9
Create Date: 2021-03-17 16:04:11.787178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd5cefabf099'
down_revision = '788507884df9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('course_tag_text_key', 'course_tag', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('course_tag_text_key', 'course_tag', ['text'])
    # ### end Alembic commands ###
