"""empty message

Revision ID: e076199d4601
Revises: c1b26370fe31
Create Date: 2021-03-19 03:51:58.580210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e076199d4601'
down_revision = 'c1b26370fe31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_learning_objectives', sa.Column('course_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'course_learning_objectives', 'course', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course_learning_objectives', type_='foreignkey')
    op.drop_column('course_learning_objectives', 'course_id')
    # ### end Alembic commands ###
