"""empty message

Revision ID: f853e4374a7a
Revises: 478508971b0e
Create Date: 2021-03-15 20:14:03.880110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f853e4374a7a'
down_revision = '478508971b0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'course_tag', ['text'])
    op.drop_constraint('course_tag_course_id_fkey', 'course_tag', type_='foreignkey')
    op.create_foreign_key(None, 'course_tag', 'course', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'review_comment', 'course_review', ['review_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review_comment', type_='foreignkey')
    op.drop_constraint(None, 'course_tag', type_='foreignkey')
    op.create_foreign_key('course_tag_course_id_fkey', 'course_tag', 'course', ['course_id'], ['id'])
    op.drop_constraint(None, 'course_tag', type_='unique')
    op.drop_table('course_review')
    # ### end Alembic commands ###
