"""empty message

Revision ID: ffd9be783085
Revises: 24ea42838ce5
Create Date: 2021-03-21 02:22:59.569822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffd9be783085'
down_revision = '24ea42838ce5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_tag', sa.Column('slug', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_tag', 'slug')
    # ### end Alembic commands ###
